#Name of the application
spring: 
  application: 
    name:  interviewpanel-api-gateway-server
  data: 
    mongodb: 
      authentication-database: admin
      username: selva
      password: selva
      database: test
      port: 27017
      host: localhost
     # uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false

#This is a eureka server so no need to register
#eureka.client.register-with-eureka=false
#This is a eureka server no need to fetch registry
#eureka.client.fetch-registry=true
#Register url for client
#eureka.client.service-url.defaultZone=http://localhost:8761/
#timeout
#eureka.server.wait-time-in-ms-when-sync-empty=0
#All url come with prefix/api will interpret
#zuul.routes.middleware.url=http://localhost:8081/

zuul: 
  routes: 
     cart: 
       path: /cart/**
       serviceId: CART-SERVICE
     config:
       path: /config/**
       serviceId: CONFIG-SERVER
     maths:  
       path: /maths/**
       serviceId: MATHS-SERVICE
     interviewpanel-qa:
       path: /interviewpanel/qa/**
       serviceId: INTERVIEWPANEL-MS-QUESTIONANDANSWER-SERVICE
     interviewpanel-user:
       path: /interviewpanel/user/**
       serviceId: INTERVIEWPANEL-MS-USER-SERVICE
     interviewpanel-notification:
       path: /interviewpanel/notification/**
       serviceId: INTERVIEWPANEL-MS-NOTIFICATION-SERVICE
  prefix: /api
  host:
    connect-timeout-millis: 100000
    
       
server: 
  port: 8080

#spring data mongo
#spring.datasource.url=mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false
 
  


