server:
  port: 8081
  
spring:
  application:
    name: interviewpanel-ms-questionandanswer-service
  data: 
    mongodb: 
      authentication-database: admin
      username: selva
      password: selva
      database: test
      port: 27017
      host: localhost
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - http://localhost:9092
      bindings:
        output:
          destination: NEW_QUESTIONS_POSTED_TOPIC